export const CountriesOptions = [
  { value: 'Afghanistan', label: { en: 'Afghanistan', de: 'Afghanistan' } },
  { value: 'Albania', label: { en: 'Albania', de: 'Albanien' } },
  { value: 'Algeria', label: { en: 'Algeria', de: 'Algerien' } },
  { value: 'Andorra', label: { en: 'Andorra', de: 'Andorra' } },
  { value: 'Angola', label: { en: 'Angola', de: 'Angola' } },
  { value: 'Argentina', label: { en: 'Argentina', de: 'Argentinien' } },
  { value: 'Armenia', label: { en: 'Armenia', de: 'Armenien' } },
  { value: 'Australia', label: { en: 'Australia', de: 'Australien' } },
  { value: 'Austria', label: { en: 'Austria', de: 'Österreich' } },
  { value: 'Azerbaijan', label: { en: 'Azerbaijan', de: 'Aserbaidschan' } },
  { value: 'Bahrain', label: { en: 'Bahrain', de: 'Bahrain' } },
  { value: 'Bangladesh', label: { en: 'Bangladesh', de: 'Bangladesch' } },
  { value: 'Belarus', label: { en: 'Belarus', de: 'Weißrussland' } },
  { value: 'Belgium', label: { en: 'Belgium', de: 'Belgien' } },
  { value: 'Brazil', label: { en: 'Brazil', de: 'Brasilien' } },
  { value: 'Bulgaria', label: { en: 'Bulgaria', de: 'Bulgarien' } },
  { value: 'Canada', label: { en: 'Canada', de: 'Kanada' } },
  { value: 'China', label: { en: 'China', de: 'China' } },
  { value: 'Colombia', label: { en: 'Colombia', de: 'Kolumbien' } },
  { value: 'Croatia', label: { en: 'Croatia', de: 'Kroatien' } },
  {
    value: 'Czech Republic',
    label: { en: 'Czech Republic', de: 'Tschechien' },
  },
  { value: 'Denmark', label: { en: 'Denmark', de: 'Dänemark' } },
  { value: 'Egypt', label: { en: 'Egypt', de: 'Ägypten' } },
  { value: 'Estonia', label: { en: 'Estonia', de: 'Estland' } },
  { value: 'Finland', label: { en: 'Finland', de: 'Finnland' } },
  { value: 'France', label: { en: 'France', de: 'Frankreich' } },
  { value: 'Germany', label: { en: 'Germany', de: 'Deutschland' } },
  { value: 'Morocco', label: { en: 'Morocco', de: 'Marokko' } },
  { value: 'Greece', label: { en: 'Greece', de: 'Griechenland' } },
  { value: 'Hungary', label: { en: 'Hungary', de: 'Ungarn' } },
  { value: 'India', label: { en: 'India', de: 'Indien' } },
  { value: 'Indonesia', label: { en: 'Indonesia', de: 'Indonesien' } },
  { value: 'Iran', label: { en: 'Iran', de: 'Iran' } },
  { value: 'Iraq', label: { en: 'Iraq', de: 'Irak' } },
  { value: 'Ireland', label: { en: 'Ireland', de: 'Irland' } },
  { value: 'Israel', label: { en: 'Israel', de: 'Israel' } },
  { value: 'Italy', label: { en: 'Italy', de: 'Italien' } },
  { value: 'Japan', label: { en: 'Japan', de: 'Japan' } },
  { value: 'Kazakhstan', label: { en: 'Kazakhstan', de: 'Kasachstan' } },
  { value: 'Kenya', label: { en: 'Kenya', de: 'Kenia' } },
  { value: 'Kuwait', label: { en: 'Kuwait', de: 'Kuwait' } },
  { value: 'Latvia', label: { en: 'Latvia', de: 'Lettland' } },
  { value: 'Lithuania', label: { en: 'Lithuania', de: 'Litauen' } },
  { value: 'Malaysia', label: { en: 'Malaysia', de: 'Malaysia' } },
  { value: 'Mexico', label: { en: 'Mexico', de: 'Mexiko' } },
  { value: 'Netherlands', label: { en: 'Netherlands', de: 'Niederlande' } },
  { value: 'New Zealand', label: { en: 'New Zealand', de: 'Neuseeland' } },
  { value: 'Nigeria', label: { en: 'Nigeria', de: 'Nigeria' } },
  { value: 'Norway', label: { en: 'Norway', de: 'Norwegen' } },
  { value: 'Pakistan', label: { en: 'Pakistan', de: 'Pakistan' } },
  { value: 'Philippines', label: { en: 'Philippines', de: 'Philippinen' } },
  { value: 'Poland', label: { en: 'Poland', de: 'Polen' } },
  { value: 'Portugal', label: { en: 'Portugal', de: 'Portugal' } },
  { value: 'Romania', label: { en: 'Romania', de: 'Rumänien' } },
  { value: 'Russia', label: { en: 'Russia', de: 'Russland' } },
  { value: 'Saudi Arabia', label: { en: 'Saudi Arabia', de: 'Saudi-Arabien' } },
  { value: 'Serbia', label: { en: 'Serbia', de: 'Serbien' } },
  { value: 'Singapore', label: { en: 'Singapore', de: 'Singapur' } },
  { value: 'Slovakia', label: { en: 'Slovakia', de: 'Slowakei' } },
  { value: 'South Africa', label: { en: 'South Africa', de: 'Südafrika' } },
  { value: 'South Korea', label: { en: 'South Korea', de: 'Südkorea' } },
  { value: 'Spain', label: { en: 'Spain', de: 'Spanien' } },
  { value: 'Sri Lanka', label: { en: 'Sri Lanka', de: 'Sri Lanka' } },
  { value: 'Sweden', label: { en: 'Sweden', de: 'Schweden' } },
  { value: 'Switzerland', label: { en: 'Switzerland', de: 'Schweiz' } },
  { value: 'Thailand', label: { en: 'Thailand', de: 'Thailand' } },
  { value: 'Turkey', label: { en: 'Turkey', de: 'Türkei' } },
  { value: 'Ukraine', label: { en: 'Ukraine', de: 'Ukraine' } },
  {
    value: 'United Kingdom',
    label: { en: 'United Kingdom', de: 'Vereinigtes Königreich' },
  },
  {
    value: 'United States',
    label: { en: 'United States', de: 'Vereinigte Staaten' },
  },
];
