import '@wexelcode/theme';

import { AuthProvider } from '@wexelcode/auth';
import { QueryProvider } from '@wexelcode/react-query';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

import MainLayout from '../../layouts/main-layout';
import { routing } from './../../i18n/routing';

export const metadata = {
  title: 'WexelCode Patient',
  description: 'Generated by create-nx-workspace',
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // Ensure `params` is awaited before accessing its properties
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Fetch translations/messages
  const messages = await getMessages();

  return (
    <AuthProvider>
      <html lang={locale}>
        <body>
          <QueryProvider>
            <NextIntlClientProvider messages={messages}>
              <MainLayout>{children}</MainLayout>
            </NextIntlClientProvider>
          </QueryProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
