import '@wexelcode/theme';

import { DashboardLayout } from '@wexelcode/layouts';

import { UserMenu } from '../user-menu';

export const metadata = {
  title: 'WexelCode Patient',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <DashboardLayout navigationItems={[]} userMenu={<UserMenu />}>
          {children}
        </DashboardLayout>
      </body>
    </html>
  );
}
