import { DashboardLayout } from '@wexelcode/layouts';
import { ThemeProvider } from '@wexelcode/theme';

import { UserMenu } from '../user-menu';

export const metadata = {
  title: 'WexelCode Patient',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body>
          <DashboardLayout navigationItems={[]} userMenu={<UserMenu />}>
            {children}
          </DashboardLayout>
        </body>
      </html>
    </ThemeProvider>
  );
}
