name: CI

on:
  push:
    branches:
    - dev
    - feature/ci-cd
  pull_request:


permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Cache node_modules
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - run: npm install -g pnpm
    - run: pnpm install --frozen-lockfile

    # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
    # - run: npx nx-cloud record -- echo Hello World
    # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
    - name: Sets the base and head SHAs for the nx affected commands in CI
      uses: nrwl/nx-set-shas@v4

    - name: Build affected libs
      run: npx nx affected -t build --verbose

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v2
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ vars.AWS_REGION }}

    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v2

    - name: Get affected projects
      id: affected
      run: echo "APPS=$(npx nx show projects --affected | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Check affected
      if: contains(env.APPS, 'patient-portal')
      run: echo "patient-portal is affected!"
      run: cd apps/patient-portal

    # - name: Build and push Docker image to ECR
    #   id: image
    #   env:
    #     ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
    #     ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
    #     IMAGE_TAG: ${{ github.run_number }}
    #   run: |
    #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    #     echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
