name: CI

on:
  push:
    branches:
    - dev
    - feature/ci-cd
  pull_request:


permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Cache node_modules
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - run: npm install -g pnpm
    - run: pnpm install --frozen-lockfile

    # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
    # - run: npx nx-cloud record -- echo Hello World
    # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
    - name: Sets the base and head SHAs for the nx affected commands in CI
      uses: nrwl/nx-set-shas@v4

    - name: Build affected libs
      run: npx nx affected -t build --verbose

    - name: Get affected projects
      id: affected
      run: echo "APPS=$(npx nx show projects --affected | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Check affected
      if: contains(env.APPS, 'patient-portal')
    - run: echo "patient-portal is affected!"
    - run: cd apps/patient-portal

